[versions]
androidGradlePlugin = "8.3.2"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"

activityCompose = "1.9.0"
barcodeScanning = "17.2.0"
cameraCamera2 = "1.3.3"
coilCompose = "2.6.0"
composeBom = "2024.04.01"
composeMaterial = "1.3.1"
zxing = "3.5.3"
coreKtx = "1.13.0"
datastorePreferences = "1.1.0"
hiltAndroid = "2.51.1"
hiltNavigationCompose = "1.2.0"
lifecycleRuntimeKtx = "2.7.0"
loggingInterceptor = "4.12.0"
material3 = "1.2.1"
moshiKotlin = "1.15.1"
navigationCompose = "2.7.7"
retrofit = "2.11.0"
uiTooling = "1.6.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

androidx-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationCompose" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }

androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraCamera2" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraCamera2" }

androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcodeScanning" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android" , version.ref = "kotlin"}
daggerHiltAndroid = { id = "com.google.dagger.hilt.android" , version.ref = "hiltAndroid"}
devtoolsKsp = {  id = "com.google.devtools.ksp" , version.ref = "ksp" }